### ISSUE TITLE
Implement DOM diffing

### ISSUE THREAD

**Issue by aaronc** [aaronc/freactive#11]
Not necessary in most cases based on freactive's other optimizations, but good to have. The plan is to implement naive diffing and not support "keys" (items-view type components should be used instead).

**Comment by noprompt** [comment]
If you're planning to implement this feature, my suggestion would be to not package it with this library (unless you want that sort of tight coupling). Having a DOM diffing library as a standalone package would be better for the community as a whole. :smile:

**Comment by aaronc** [comment]
So, DOM diffing is actually implemented in master (the core logic is in these lines: https://github.com/aaronc/freactive/blob/master/src/clojure/freactive/dom.cljs#L578-L622 and this part is pretty essential too: https://github.com/aaronc/freactive/blob/master/src/clojure/freactive/dom.cljs#L443-L499) - I'm just working through a few bugs related to rebinding reactive nodes. I have thought about putting the diffing code in a separate namespace and having it as a feature that can be enabled/disabled. I'm not too sure, however, that it would make sense to have sort of a generic "diffing" algorithm - at least based on this code. The reason is that the diffing logic itself is quite trivial whereas the complex part is dealing with the fact that freactive has to disable and enable direct bindings on attributes and nodes - so basically, I don't really see a way to do it in freactive that isn't related to the core code for tracking bindings. Also, my reason for being able to enable/disable diffing is actually more related to the fact that in freactive, most of the magic is done by direct binding and diffing only adds a small (but measurable) performance enhancement for certain cases.

**Comment by jfbaro** [comment]
You guys probably know about tis already:

https://localvoid.github.io/vdom-benchmark/

**Comment by aaronc** [comment]
Wasn't aware of it, but I imagine freactive probably wouldn't do as good in pure diffing ;) I think needing to walk Clojurescript seq's and maps as well as disabling reactive bindings adds a significant performance hit

But it may be useful to have know how fast its diffing is in any event...

**Comment by aaronc** [comment]
The current `develop` branch already features quite good reactive sequence binding (documentation forthcoming) so diffing really adds little to the feature set. Diffing has been implemented successfully in the `experimental-diffing` branch but given the other features already present it adds little benefit that can not be handled better with direct binding - not planning to merge unless there is a compelling reason down the road.
