### ISSUE TITLE
Dereferencing to automatically trigger an update... like Reagent

### ISSUE THREAD

**Issue by Frozenlock** [aaronc/freactive#16]
First of all, this is amazing stuff.

The notion of having a pure cljs 'react' is very exciting.
Being able to use _any_ tag is very convenient.

I was wondering if it was possible to somehow do the same thing as reagent:
No need for `rx`, the simple act of deferencing capture everything that's needed.

> Any component that dereferences a reagent.core/atom will be automatically re-rendered.

**Comment by ul** [comment]
I think this contradicts a little bit to core idea of freactive. Because, as far as I understand, freactive tries to deliver changes to exact place (dom node, attributes or styles), not to entire component.

**Comment by aaronc** [comment]
Yeah, so as Ruslan was just explaining the model for freactive is a bit different. A component in freactive is basically created by passing something that is "derefable" (implements `cljs.core/IDeref`) and watchable (implements `cljs.core/IWatchable` and/or `freactive.core/IInvalidates`) as a child node or attribute.  There is no other type of component. So, if you want to get reactive binding you'll need to have something that is "derefable" and watchable. The `rx` macro does not create a component itself but just something that is "deferable" and watchable which returns an up-to-date representation of your user interface whenever it is deref'ed. The framework then knows how to make a binding on that "derefable"/watchable thing - this binding could have lifecycle callbacks a la React.

So, it is a slightly different model. After talking with several people at Clojure/conj about this, I realize that the way this model works may need a bit more explaining than I've given it so I definitely intend to write some more detailed docs about this. For those coming from the React/Reagent/Om model, I think what I'm doing may seem a little strange at first, but I'm pretty sure that once one "groks" it, it will make sense... What it allows one to do is direct binding which is inherently more efficient than diffing for most cases (I do have experimental diffing to support other cases if that should be needed).

So the Regeant syntax for component instantiation - although it is less typing - may not be more clear. In my mind, it adds a degree of "complection" (using Rich Hickey's terminology) which just isn't necessary once we have our own component (binding) model not tied to React.

Let me know if this explanation makes sense. I'm trying to figure out the best way to communicate this model.

**Comment by sparkofreason** [comment]
Is this why add-watch doesn't seem to work with an rx expression? See

https://gist.github.com/sparkofreason/a42420c3f9572de5c82d

I never see output for the :c*d watch.

**Comment by aaronc** [comment]
`add-watch` should work on `rx`'s. Could be a bug in `0.1.0` though. Have you tried it with `0.2.0-SNAPSHOT`? Also you probably just want to use `(cursor x :b)`, `(cursor b :c)` in most cases...

**Comment by sparkofreason** [comment]
I tried with both 0.1.0 and 0.2.0-SNAPSHOT, same result.

Agreed on using `(cursor x :b)` form, I'm just playing around to get my head around the whole lens/cursor idea in general.

**Comment by aaronc** [comment]
If you try dereferencing the c*d before you add the watch does that help?

**Comment by aaronc** [comment]
Oops, I looked at your example again and see that you're doing that. Just
trying to think about what could be causing this bug...

**Comment by sparkofreason** [comment]
Actually, it works if I deref it twice before adding the watch.

**Comment by aaronc** [comment]
Looks like this is a good case for me to debug before the next release.
There is a concept of laziness in the current implementation, but I think
that often ends up in things being too lazy. The atom/cursor infrastructure
will probably go through some pretty thorough refactoring before I call it
stable. FYI freactive should work with other atom/rx implementations such
as javelin which may be more stable right now.

**Comment by sparkofreason** [comment]
Thanks, will look into other implementations if I need them. Not sure I will, as long as DOM updates work correctly. I'm experimenting using freactive to build HTML custom elements in ClojureScript (https://github.com/allgress/cereus). Looks pretty solid so far (albeit with very limited testing), and a vast improvement over my previous attempt using React-like virtual DOM.

**Comment by aaronc** [comment]
Nice :)

**Comment by GetContented** [comment]
It's possible that issue 44 would solve this issue... https://github.com/aaronc/freactive/issues/44 (rallying support)

**Comment by aaronc** [comment]
`0.2.0` will probably support Reagent's `[my-component-fn ...]` either by default or via some plugin.

**Comment by aaronc** [comment]
Reagent's `[my-component-fn ...]` syntax is now supported in the `develop` branch because it was very easy to implement and this may make it easier for some people to get started. It is however officially "discouraged" (as it encourages less-direct binding than freactive supports). Reagent's `with-meta` callbacks are obviously not supported. Closing this.
