### ISSUE TITLE
freactive does not support :style  in hiccup like notation

### ISSUE THREAD

**Issue by sveri** [aaronc/freactive#18]
I tried this:
[:div#success {:class "alert alert-success" :style "display:none"}]
and it compiles without warnings but when I open the page I get this error:

Uncaught Error: Assert failed: (map? attr-value) dom.cljs:226bind_attr_BANG_ dom.cljs:226(anonymous function) dom.cljs:456build_element dom.cljs:459append_child dom.cljs:278replace_or_append_child dom.cljs:289do_show_element dom.cljs:300transition_element dom.cljs:314append_child_BANG_ dom.cljs:433append_children_BANG_ dom.cljs:439(anonymous function) dom.cljs:458build_element dom.cljs:459append_child dom.cljs:278replace_or_append_child dom.cljs:289(anonymous function) dom.cljs:357append_deref_child dom.cljs:417append_child_BANG_ dom.cljs:430append_children_BANG_ dom.cljs:441append_children_BANG_ dom.cljs:440(anonymous function) dom.cljs:458build_element dom.cljs:459append_child dom.cljs:278replace_or_append_child dom.cljs:289do_show_element dom.cljs:300transition_element dom.cljs:314append_child_BANG_ dom.cljs:433append_children_BANG_ dom.cljs:439(anonymous function) dom.cljs:458build_element dom.cljs:459append_child dom.cljs:278replace_or_append_child dom.cljs:289do_show_element dom.cljs:300transition_element dom.cljs:314append_child_BANG_ dom.cljs:433mount_BANG_ dom.cljs:466main core.cljs:22(anonymous function)

And:
Uncaught TypeError: Cannot read property 'nodeType' of null dom.cljs:18dom_node_QMARK_ dom.cljs:18get_element_spec dom.cljs:54get_transition dom.cljs:107animate dom.cljs:373render

**Comment by aaronc** [comment]
Hi sveri, so the way freactive supports :style is by supporting a map of properties. This allows one to do binding direct to style properties - which could be pretty useful for animation. The stack trace (which I agree is unreadable) is trying to tell you that the attribute value (attr-value) should be a map (therefore Assert failed: (map? attr-value)

Try this:

``` clj
[:div#success {:class "alert alert-success" :style {:display "none"}}]
```

**Comment by sveri** [comment]
Thank you, that does the trick. I wonder if this is documented somewhere in the hiccup docu? I did not find anthing.

**Comment by aaronc** [comment]
Well this is documented for freactive. Hiccup probably does it the way you
expected.

**Comment by sveri** [comment]
Sorry, I have been reading the docs like three times, but missed that obvious example.
