### ISSUE TITLE
No protocol method IWithMeta.-with-meta defined 

### ISSUE THREAD

**Issue by tony-landis** [aaronc/freactive#28]
I have created a cursor using with-meta:

``` (clojure)
  (with-meta 
    (cursor a path)
    {:path path
     :atom a}) 
```

Attempting to use the cursor throws this exception:

```
No protocol method IWithMeta.-with-meta defined for type freactive.core/ReactiveCursor
```

It would be great to be able to have metadata on cursors. 

Thanks!

**Comment by aaronc** [comment]
Cursors, like other "ref"s should support `alter-meta!`

**Comment by tony-landis** [comment]
Thanks Aaron. For an app I am building, it is very useful to track a cursor's parent iref and the key sequence. I was able to implement a helper fn to accomplish this using `alter-meta!`

``` (clojure```
(defn cursor!
  [iref key-s]
  "builds a cursor with metadata to track its parent "
  (let [c (cursor iref key-s) ]
    (alter-meta! c assoc :iref iref :key-s key-s)
    c))
```

**Comment by aaronc** [comment]
Do you think this is important enough to put into core?

I'm thinking something like this:

``` clj
(defn cursor* [ref korks-or-getter setter lazy]
  (let [ks (cond
            (keyword? korks-or-getter)
            [korks-or-getter]

            (sequential? korks-or-getter)
            korks-or-getter)
...
        cursor (ReactiveCursor. ref getter setter true nil nil nil nil lazy nil nil)]
...
     (when ks
       (let [{:keys [root path]} (meta ref)
              path-info (if (and root path)
                               {:root root :path (concat path ks)}
                               {:root ref :path ks})]
           (alter-meta! cursor merge path-info)))
     cursor))
```

That would capture the path back to the root if available. What do you think?
