### ISSUE TITLE
Infinite loop when creating cursor inside an rx expression

### ISSUE THREAD

**Issue by sparkofreason** [aaronc/freactive#39]
See https://gist.github.com/sparkofreason/8bdbde5d60137f84c9b6.

This results in an infinite loop of evaluating the rx expression. This may not be a valid use, but perhaps it would be better to have an exception thrown.

**Comment by sparkofreason** [comment]
Noticed something else here: if I wrap the let-binding of b in it's own rx, then the infinite loop behavior goes away.

**Comment by aaronc** [comment]
I wouldn't say this is invalid use, but usually you'd at least want to do something like this where the de-referencing of the child cursor is in its own rx so the cursor is not necessarily re-created whenever its value changes:

``` clj
(rx
 (let [b (cursor state :b)]
  (rx (do-something-with @b))))
```

Still looks like, this is probably a valid bug so I'll take a look when I get a chance.

**Comment by aaronc** [comment]
Is this still an issue with the new cursor implementation?

**Comment by sparkofreason** [comment]
No, looks good. I'll close.
