### ISSUE TITLE
rx-expression with child cursor does not update correctly

### ISSUE THREAD

**Issue by sparkofreason** [aaronc/freactive#46]
Please see [https://gist.github.com/sparkofreason/8bdbde5d60137f84c9b6](https://gist.github.com/sparkofreason/8bdbde5d60137f84c9b6). The output here is 

```
d = 3
(b :d) = 5
```

Would expect both to be 5.

**Comment by aaronc** [comment]
So it's the cursor `(cursor state [:b :d])` that's not updating correctly, not the rx correct?

**Comment by sparkofreason** [comment]
Correct.

**Comment by aaronc** [comment]
Okay, I'll check it out.

**Comment by aaronc** [comment]
Should be fixed now - let me know if you still have the issue. The `freactive.core` namespace was moved to the the freactive.core project by the way: https://github.com/aaronc/freactive.core. Snapshots have been pushed to clojars.

**Comment by sparkofreason** [comment]
All fixed - thank you. Closing.
