### ISSUE TITLE
Is mounting the document.body unsupported?

### ISSUE THREAD

**Issue by pkobrien** [aaronc/freactive#48]
For example:

```
(dom/mount! js/document.body [:body]))
```

It might not be a good idea to do so, but other dom manipulation tools support it. If this is a bad idea in freactive, then the error one gets is unhelpful and should be improved. Thanks.

**Comment by aaronc** [comment]
Mounting in freactive does not replace the element you are mounting.
Mounting clears all of an element's children and replaces them with the
content being mounted. What you are doing would result in
<body><body></body><body></body>. Have you tried (dom/mount!
js/document.body [:h1 "Hello World"])?

**Comment by pkobrien** [comment]
Oh, I see! My mistake then. I'm new to clojure (started 4 weeks ago) and have been working on a few projects using re-frame, reagent, and om, just to get my feet wet. I just started working with freactive and obviously made some wrong assumptions. Now I'm curious to know what's been going on with those other tools. I _thought_ that they all _replaced_ the target that they were mounting, but perhaps they were not. In any case, freactive is working as intended so I will close this issue. Thanks. :-)

**Comment by pkobrien** [comment]
Hmm. I'm still having a problem. I can change :body to :div as in the code below, but mounting the document.body is still giving me an error vs. mounting a div.

```
(defn app-html []
  [:div
   [:header
    [:h1 "Header Level 1"]
    ]
   [:main
    [:p "Main content goes here."]
    ]
   [:footer
    [:p "Footer content. Mouse position: " (rx (str "(" @mouse-x ", " @mouse-y ")"))]
    ]
   ])

(defn init []
  (set-title (:app-name app-state))
;  (dom/mount! js/document.body (app-html)))
  (dom/mount! "app-div" (app-html)))
```

I'm not trying to do both mounts, just leaving them both in the code to show the one that doesn't work, which is commented out, and the one that does work.

**Comment by aaronc** [comment]
What error are you getting? Overall I wouldn't think mounting body would be
such a good idea as it prevents other things (like scripts) from going
there.

**Comment by pkobrien** [comment]
I'm starting to see that my approach of trying to keep things simple and clean by working at the level of body is probably misguided and that I just got lucky with the other tools. Mounting a div makes total sense now. Thanks for helping me see the light. ;-)
