### ISSUE TITLE
Sorting algorithms for items-view

### ISSUE THREAD

**Issue by aaronc** [aaronc/freactive#5]
Efficient algorithms for applying stable (possible in place) sorting to the `items-view`

**Comment by aaronc** [comment]
Implemented in `develop` branch via `data.avl`.

**Comment by ul** [comment]
be aware, that cljs version of data.avl has an error (not sure if it affect freactive): http://dev.clojure.org/jira/browse/DAVL-6

**Comment by aaronc** [comment]
Thx. Don't think I'm using those methods but hopefully they'll fix it.
